# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'I_ExpressionRecordUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_I_ExpressionRecordForm(object):
    def setupUi(self, I_ExpressionRecordForm):
        I_ExpressionRecordForm.setObjectName("I_ExpressionRecordForm")
        I_ExpressionRecordForm.resize(400, 40)
        I_ExpressionRecordForm.setMinimumSize(QtCore.QSize(0, 40))
        I_ExpressionRecordForm.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(11)
        I_ExpressionRecordForm.setFont(font)
        self.horizontalLayout = QtWidgets.QHBoxLayout(I_ExpressionRecordForm)
        self.horizontalLayout.setContentsMargins(6, 0, 6, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(I_ExpressionRecordForm)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(12)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_3.addWidget(self.checkBox, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.name_label = QtWidgets.QLabel(self.widget)
        self.name_label.setText("")
        self.name_label.setWordWrap(True)
        self.name_label.setObjectName("name_label")
        self.horizontalLayout_2.addWidget(self.name_label)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(I_ExpressionRecordForm)
        QtCore.QMetaObject.connectSlotsByName(I_ExpressionRecordForm)

    def retranslateUi(self, I_ExpressionRecordForm):
        _translate = QtCore.QCoreApplication.translate
        I_ExpressionRecordForm.setWindowTitle(_translate("I_ExpressionRecordForm", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    I_ExpressionRecordForm = QtWidgets.QWidget()
    ui = Ui_I_ExpressionRecordForm()
    ui.setupUi(I_ExpressionRecordForm)
    I_ExpressionRecordForm.show()
    sys.exit(app.exec_())
